language: php
php:
  - 7.0
sudo: required
dist: trusty
before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
  - sudo add-apt-repository -y ppa:pinepain/libv8-5.4
  - sudo apt-get update -y
  - sudo apt-get install -y libv8-5.4-dev
  - git clone https://github.com/pinepain/php-v8.git
  - cd php-v8 && phpize && ./configure && make
  - echo "extension=v8.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
  - composer install
script:
  - vendor/bin/phpunit
